[package]
name = "erris"
version = "2.1.0"
edition = "2024"
description = "Errors, explained."
license = "MIT OR Apache-2.0"
repository = "https://github.com/volkagames/erris"
readme = "README.md"
keywords = ["error", "diagnostics", "report", "trace"]
categories = ["rust-patterns", "development-tools::debugging"]

[features]
default = ["spantrace", "to_json"]
spantrace = [
    "dep:tracing-core",
    "dep:tracing-error",
    "dep:tracing-subscriber",
    "dep:tracing",
    "erris-meta/spantrace",
]
backtrace = []
keep-duplicate-location = []
to_json = ["dep:serde_json", "dep:serde", "spantrace"]
valuable = [
    "spantrace",
    "dep:tracing-core",
    "dep:valuable",
    "dep:valuable-serde",
    "tracing-core/valuable",
]

[dependencies]
erris-meta = { version = "1", path = "../erris-meta" }
indenter = { version = "0.3", features = ["std"] }
serde = { version = "1.0.228", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }
tracing = { version = "0.1.44", optional = true }
tracing-core = { version = "0.1", optional = true }
tracing-error = { version = "0.2", optional = true }
tracing-subscriber = { version = "0.3.23", optional = true }
valuable = { version = "0.1.1", optional = true }
valuable-serde = { version = "0.1.1", optional = true }

[dev-dependencies]
erris-meta = { version = "1", path = "../erris-meta" }
rusty-fork = "0.3.1"
thiserror = "2.0.18"
tracing-log = "0.2"
